#-------------------------------------------------------------------------------
# View 

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  colorscheme nord
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {'colorscheme': 'nord'}
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Yggdroot/indentLine'

#-------------------------------------------------------------------------------
# Lint & Completion

[[plugins]]
repo = 'mattn/emmet-vim'

#-------------------------------------------------------------------------------
# Syntax

[[plugins]]
on_ft = 'toml'
repo = 'cespare/vim-toml'

[[plugins]]
on_ft = 'typescript'
repo = 'leafgarland/typescript-vim'

[[plugins]]
on_ft = 'typescript'
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
on_ft = 'typescript'
repo = 'maxmellon/vim-jsx-pretty'

