#-------------------------------------------------------------------------------
# View 

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  colorscheme nord
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {'colorscheme': 'nord'}
  " let g:lightline = {'colorscheme': 'PaperColor'}
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Yggdroot/indentLine'

#-------------------------------------------------------------------------------
# Lint & Completion

# [[plugins]]
# repo = 'Shougo/vimproc.vim'
# build = 'make'

[[plugins]]
repo = 'mattn/emmet-vim'

# [[plugins]]
# repo = 'w0rp/ale'
# hook_add = '''
#   " key mapping
#   nmap <silent> <SPACE>j <Plug>(ale_next_wrap)
#   nmap <silent> <SPACE>k <Plug>(ale_previous_wrap)
#   " general settings
#   let g:ale_open_list = 0
#   let g:ale_list_window_size = 5
#   let g:ale_lint_delay = 1000
#   let g:ale_lint_on_enter = 0
#   " custom message and sign
#   let g:ale_echo_msg_error_str = '[ERROR]'
#   let g:ale_echo_msg_warning_str = '[WARNING]'
#   let g:ale_sign_error = "\uf41b"
#   let g:ale_sign_warning = "\uf420"
#   " linter setting
#   let g:ale_linters = {
#     \ 'python': ['flake8'],
#     \ 'sh': ['shellcheck'],
#     \ }
#   let g:ale_python_flake8_args="--max-line-length=120"
# '''


#-------------------------------------------------------------------------------
# Syntax

[[plugins]]
on_ft = 'toml'
repo = 'cespare/vim-toml'

[[plugins]]
on_ft = 'typescript'
repo = 'leafgarland/typescript-vim'

[[plugins]]
on_ft = 'typescript'
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
on_ft = 'typescript'
repo = 'maxmellon/vim-jsx-pretty'

