[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
'''
# 
# [[plugins]]
# repo = 'roxma/nvim-yarp'
# 
# [[plugins]]
# repo = 'roxma/vim-hug-neovim-rpc'

# [[plugins]]
# repo = 'davidhalter/jedi-vim'
# on_ft = 'python'
# hook_source = '''
# let g:jedi#auto_initialization = 0
# let g:jedi#auto_vim_configuration = 0
# let g:jedi#smart_auto_mappings = 0
# let g:jedi#completions_enabled = 0
# let g:jedi#goto_command = "<Leader>d"
# '''
